name: tekartik_firebase_storage_fs
description: Firebase storage fs
version: 0.4.7
publish_to: none
#homepage: https://www.example.com
#

environment:
  sdk: ^3.7.0

dependencies:
  fs_shim: ">=2.3.3+1"
  uuid: '>=1.0.0'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart3a
    version: '>=0.4.0'
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart3a
    version: '>=0.9.0'
  process_run: ">=1.2.1+1"
  crypto:
  path: ">=1.9.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
dev_dependencies:
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: ">=0.10.3"
  tekartik_firebase_storage_test:
    path: ../storage_test
  http:

resolution: workspace
  #TODO
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase
