name: tekartik_firebase_storage_fs
description: Firebase storage fs
version: 0.4.0+1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.7.0-dev <3.0.0'

dependencies:
  fs_shim: '>=0.11.0+2'
  uuid: '>=1.0.0'
  tekartik_firebase_storage:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart2
    version: 0.4.0
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
    version: '>=0.4.0'
  process_run: '>=0.10.2'

dev_dependencies:
  test: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  tekartik_firebase_storage_test:
    path: ../storage_test

dependency_overrides:
  tekartik_firebase_storage:
    path: ../storage
  #TODO
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase