name: tekartik_firebase_storage_fs
description: Firebase storage fs
version: 0.4.7
publish_to: none
#homepage: https://www.example.com
#

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fs_shim: '>=1.0.2+1'
  uuid: '>=1.0.0'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart2_3
    version: '>=0.4.0'
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2_3
    version: '>=0.9.0'
  process_run: '>=0.10.2'

dev_dependencies:
  test: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  tekartik_firebase_storage_test:
    path: ../storage_test
  http:

dependency_overrides:
  tekartik_firebase_storage:
    path: ../storage
  #TODO
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase