name: tekartik_firebase_storage_browser
description: Firebase storage browser
version: 0.4.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart3a
      version: '>=0.4.0'
  tekartik_firebase_browser:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: dart3a
    version: '>=0.4.0'
  firebase: '>=5.0.2'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a

dev_dependencies:
  test: ">=0.12.37"
  dev_build: '>=0.12.0-dev.1'
  http: any
  yaml: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  build_web_compilers: ">=0.4.0+4"
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_storage:
    path: ../storage
  tekartik_firebase_storage_test:
    path: ../storage_test
#TODO
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase
#  tekartik_firebase_browser:
#    path: ../../firebase.dart/firebase_browser
