name: tekartik_firebase_storage
description: Firebase storage core
version: 0.3.6
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.3.6'

dev_dependencies:
  test: "^1.0.0"

dependency_overrides:
  tekartik_firebase:
    path: ../../firebase.dart/firebase