name: tekartik_firebase_storage
description: Firebase storage core
version: 0.8.0

publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.4.0'
  path:
dev_dependencies:
  test: '>=1.0.0'
  process_run: '>=0.10.2'
  dev_build:

dependency_overrides:
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase
