name: tekartik_firebase_storage
description: Firebase storage core
version: 0.3.7
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.3.7'

dev_dependencies:
  test: "^1.0.0"
  process_run: '>=0.10.2'

dependency_overrides:
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase