name: tekartik_firebase_storage
description: Firebase storage core
version: 0.8.0

publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.4.0'
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"

dependency_overrides:
resolution: workspace
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase
