analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
include: package:tekartik_lints/strict.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    deprecated_member_use_from_same_package: false