name: firebase_storage_repo_support
description: Firebase storage utils repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  lints: ">=5.0.0"
  process_run: ">=1.2.1+1"
resolution: workspace


