name: firebase_storage_repo_support
description: Firebase storage utils repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  path:
  pub_semver:
  test:
  dev_build:
  lints: '>=2.0.0'
  process_run:
resolution: workspace


