name: firebase_storage_repo_support
description: Firebase storage utils repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  path:
  pub_semver:
  test:
  dev_test:
  lints:
  process_run:


