name: tekartik_firebase_storage_sim
description: Firebase simulation
version: 0.8.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  cv: ">=1.1.0+4"
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
    version: '>=0.8.0'
  meta: ">=1.15.0"
  synchronized: '>=1.5.0-dev.2'
  logging: any
  path: ">=1.9.0"
  json_rpc_2:

dev_dependencies:
  tekartik_firebase_storage_test:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_test
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test: ">=0.10.3"
  process_run: ">=1.2.1+1"

resolution: workspace
