name: tekartik_firebase_storage_test
description: Firebase storage test
version: 0.4.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.9.0

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
    version: '>=0.4.1'
  dev_test: ">=1.0.0+4"
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"

resolution: workspace
#TODO
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase
