name: tekartik_firebase_storage_test
description: Firebase storage test
version: 0.4.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart2_3
    version: '>=0.4.1'
  test: ">=1.0.0"
  path:
dev_dependencies:
  dev_test: '>=0.12.0-dev.1'
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_storage:
    path: ../storage
#TODO
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase