name: tekartik_firebase_storage_test
description: Firebase storage test
version: 0.3.6
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase_storage:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart2
    version: 0.3.6
  test: ">=1.0.0"

dev_dependencies:
  dev_test: '>=0.12.0-dev.1'

dependency_overrides:
  tekartik_firebase_storage:
    path: ../storage